export const FORM = {
  apn:"5555-012-034", county:"Los Angeles", cityOfProperty:"Pasadena",
  propertyAddress:"123 Main Street, Pasadena, CA 91101",
  legalDescription:"Lot 5 of Tract No. 12345, in the City of Pasadena, County of Los Angeles, State of California, as per map recorded in Book 200, Pages 10-12 of Maps.",
  grantor:"John Q. Public and Mary R. Public, husband and wife",
  grantorCapacity:"Individual", grantorPronoun:"they",
  grantee:"The Public Family Trust", granteeAddress:"123 Main Street, Pasadena, CA 91101",
  granteeVesting:"as Trustees of The Public Family Trust dated March 1, 2020", customVesting:"",
  dtt:"330.00", sb2Fee:"75", exemptFromTax:false, exemptReason:"R&T §11930 - transfer to a revocable trust",
  prop19:false, certify19100:false, businessPurpose:false,
  trustName:"The Public Family Trust", trustDate:"March 1, 2020", trustTransferReason:"estate planning",
  trustorName:"John Q. Public", trustorAddress:"123 Main Street, Pasadena, CA 91101",
  trustorCapacity:"Individual", trustorVesting:"a married man as his sole and separate property", trustorCustomVesting:"",
  capTrustName:"The Public Family Trust", capTrustDate:"March 1, 2020",
  beneficiaryLenderName:"Acme Lending, Inc.", beneficiaryLenderAddress:"9 Finance Way, Los Angeles, CA 90001",
  beneficiaryName:"Acme Lending, Inc.", loanAmount:"500,000", loanAmountWords:"Five Hundred Thousand", loanDate:"June 1, 2024",
  dotTrustee:"First American Title Insurance Company", dueOnSale:true, dotPosition:"first",
  seniorLienHolder:"", seniorLienRecording:"", seniorLienRecordingDate:"", seniorLienType:"", seniorLoanDate:"", requestNOD:false,
  dotModNewRate:"6.5%", dotModNewMaturity:"June 1, 2054", dotModNewAmount:"525,000", dotModPosition:"first", dotModTerms:"Interest-only for 24 months.", originalDeedDate:"June 1, 2024",
  originalDeedType:"Deed of Trust", originalDeedGrantor:"John Q. Public", originalDeedRecording:"2024-0123456", originalDeedRecordingDate:"June 5, 2024",
  spouseName:"Mary R. Public", spouseVesting:"a married woman", spouseCurrentVesting:"joint tenants", interspousalReason:"transfer between spouses", survivingSpouse:"Mary R. Public",
  decedentName:"Robert Q. Public", dateOfDeath:"January 15, 2024", survivingJointTenant:"Mary R. Public", deceasedJointTenant:"Robert Q. Public", deceasedJointTenantAKA:"Bob Public", dateOfDeathJT:"January 15, 2024",
  successorTrusteeName:"Mary R. Public", deceasedTrusteeName:"Robert Q. Public", settlorName:"Robert Q. Public", isSettlorDeceased:true,
  todOwner:"John Q. Public", todOwnerZip:"91101", todBeneficiary:"Sarah Public", todBeneficiary2:"", todBeneficiaryRelationship:"daughter", todBeneficiaryType:"individual", todEntityName:"", todTrustName:"", todTrustDate:"", todTrusteeName:"",
  reconType:"full", reconTrustee:"First American Title Insurance Company", reconNewTrustee:"", reconBeneficiary:"Acme Lending, Inc.",
  reconTrusteeSuccession:"", reconOriginalTrustee:"Old Trustee Co.", reconOriginalDeedDate:"June 1, 2024", reconRecording:"2024-0123456", reconRecordingDate:"June 5, 2024", reconLoanAmount:"500,000", reconSuccessionReason:"resignation",
  easementType:"access", easementTypeCustom:"", easementWidth:"20 feet", easementExclusive:false, easementDescription:"a right of way for ingress and egress", easementTerms:"perpetual", dominantDescription:"the adjoining parcel to the north",
  caseName:"In re Estate of Public", caseNumber:"24STPB01234", courtName:"Superior Court of California, County of Los Angeles",
  judgmentCreditor:"Acme Lending, Inc.", judgmentDebtor:"John Q. Public", judgmentDate:"March 1, 2024",
  sheriffName:"Sheriff of Los Angeles County", sheriffRedemption:true, trusteeSaleDate:"May 1, 2024", trusteeSaleLocation:"Los Angeles County Courthouse", trusteeSalePrice:"450,000", salePrice:"450,000",
  sscp_isPrimaryResidence:true, isAmended:false, customRiders:"", trusteeName:"Mary R. Public",
};
export const MASTER = {
  firmName:"Public Law Group, APC", firmAddress:"100 Attorney Plaza, Suite 400", firmCity:"Los Angeles", firmState:"California", firmZip:"90071",
  defaultTrustee:"First American Title Insurance Company", lateChargeDays:"10", lateChargePercent:"6",
  standardCovenants:"", prepaymentLanguage:"This Deed of Trust may be prepaid in whole or in part at any time without penalty.",
  provisions:[], masterVersion:1,
};
